version: '3'
services:
  es:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.4.2
    container_name: es
    environment:
      - discovery.type=single-node
    ports:
      - 9200:9200
    volumes:
      - esdata1:/usr/share/elasticsearch/data
  db:
    image: postgres
    volumes:
      - ./tmp/db:/var/lib/postgresql/data
  redis:
    image: redis:alpine
  web:
    build: .
    volumes:
      - .:/elastic_example
      - bundler-data:/usr/local/bundle/:cached
      - bin-data:/usr/local/bin/:cached
    ports:
      - "3000:3000"
    depends_on:
      - db
      - es
      - redis
volumes:
  esdata1:
    driver: local
  bundler-data:
  bin-data:
